name: Discord Webhook

on:
  workflow_run:
    workflows: [Setup]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v4.0.0
        with:
          username: "NuOJ Github Action Bot"
          avatar-url: "https://cdn.discordapp.com/attachments/989547753606631486/1009179363025092679/33.jpg"
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          embed-author-name: ${{ github.event.sender.login }}
          embed-author-icon-url: ${{ github.event.sender.avatar_url }}
          embed-author-url: ${{ github.event.sender.html_url }}
          embed-title:  ${{ format('NuOJ {0} 建置成功', github.event.workflow.name) }}
          embed-description:  ${{ format('{0}', github.event.workflow_run.head_commit.message) }}
          embed-color: 65280
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v4.0.0
        with:
          username: "NuOJ Github Action Bot"
          avatar-url: "https://cdn.discordapp.com/attachments/989547753606631486/1009179363025092679/33.jpg"
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          embed-author-name: ${{ github.event.sender.login }}
          embed-author-icon-url: ${{ github.event.sender.avatar_url }}
          embed-author-url: ${{ github.event.sender.html_url }}
          embed-title:  ${{ format('{0} 建置失敗', github.event.workflow.name) }}
          embed-description:  ${{ format('{0}', github.event.workflow_run.head_commit.message) }}
          embed-color: 16711680