name: Discord Webhook

on:
  workflow_run:
    workflows: [Setup]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v4.0.0
        with:
          username: "NuOJ Github Action Bot"
          avatar-url: "https://cdn.discordapp.com/attachments/989547753606631486/1009179363025092679/33.jpg"
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          embed-title:  ${{ format('{0} 建置成功（#{1}）', github.event.workflow.name, github.event.run_number) }}
          embed-description:  ${{ github.event.workflow_run.head_commit.message  }}
          embed-color: 65280
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v4.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          embed-title:  ${{ format('{0} 建置失敗（#{1}）', github.event.workflow.name, github.event.run_number) }}
          embed-description:  ${{ github.event.workflow_run.head_commit.message  }}
          embed-color: 16711680