name: Ubuntu 20.04

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3  
    - uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: 'mariadb-10.6'
    - name: Build
      run: |
        make install
        make sandbox-install
        make db-socket
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:      
    - name: Test
      run: make test-all