name: Ubuntu 22.04

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
  
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install
      run: |
        make install
        make sandbox-install
        make db-socket
      
    - name: NuOJ status
      run: |
        sudo systemctl start nuoj
        sudo systemctl start nuoj-sandbox
        sudo systemctl start nuoj-database
        sudo systemctl status nuoj
        sudo systemctl status nuoj-sandbox
        sudo systemctl status nuoj-database

    - name: Test
      run: make test-all