name: Ubuntu 20.04

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install
      run: make

    - name: Check NuOJ status
      run: |
        sudo systemctl start nuoj
        sudo systemctl start nuoj-sandbox
        sudo systemctl start nuoj-database
        sudo systemctl status nuoj
        sudo systemctl status nuoj-sandbox
        sudo systemctl status nuoj-database
      
    - name: Tesy
      run: make test-all