name: Ubuntu 20.04

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: 'mariadb-10.6'

    - name: Install
      run: |
        make install
        make sandbox-install
        make db-socket

    - name: Check NuOJ status
      run: |
        sudo systemctl start nuoj
        sudo systemctl start nuoj-sandbox
        sudo systemctl status nuoj
        sudo systemctl status nuoj-sandbox
      
    - name: Test
      run: make test-all
    
  webhook:
    runs-on: ubuntu-latest
    steps:
    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
        data: '"embeds": [{"title": "Test", "description": "Hello!"}]'